name: conv_onet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython
  - imageio
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - pandas
  - pillow
  - pyembree
  - pytest
  - python=3.10
  - pytorch
  - pyyaml
  - scikit-image
  - scipy
  - tensorboardx
  - torchvision
  - tqdm
  - trimesh
  - h5py
  - plyfile
  - torch_scatter